### ISSUE TITLE
Creating and sharing spreadsheets

### ISSUE THREAD

**Issue by gheye** [alphagov/data-standards-authority#11]
HI All,

To complement the work we are doing around [CSVs](https://github.com/alphagov/data-standards-authority/issues/1) we are beginning the process of some general guidance around spreadsheets, please see below. We really want to get your feedback so please comment below.

——————-

Spreadsheets are a common way to share data. This guidance will help you avoid common errors, align spreadsheets to best practice and improve interoperability.

If you plan to publish or share statistics content, you should follow the [Government Statistical Service (GSS) guidance on releasing statistics in spreadsheets](https://gss.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/). 

If your spreadsheet is for your personal use, it is still recommended to follow best practice as spreadsheets tend to grow and evolve. Spreadsheets created for personal use often end up serving a wider audience. 

If you are sharing or publishing your spreadsheet, follow this guidance to make your file easy to find, use, and to minimise risk. 

## Using spreadsheets to meet user needs
When sharing or publishing data, consider who needs access and how they will be using it. 

General users might view the information for reference only, or they might need the spreadsheet to record or submit information following specific requirements. For example, you might publish a template form for users to complete and return in order to claim back expenses. In most cases, a spreadsheet is a suitable format for these users. 

However, spreadsheets might not be suitable for technical users who want to perform detailed analysis on the information or combine it with other data. These users typically need data in machine-readable formats which they can use with programming tools with minimal data manipulation. In these cases, it might be more appropriate to [publish your data as a CSV file](https://www.gov.uk/guidance/using-csv-file-format). 

## Use a cover page
Adding a cover page to your spreadsheet helps users understand its purpose and content. This is particularly important for large or complex spreadsheets. A cover page is also useful to keep metadata and maintenance information in one place. 

Your cover page should include important information such as:

- the publisher, for example your name or department
- the date it was published
- a description of the content
- the version number of the spreadsheet

## Choose the right software for the task

Spreadsheet tools and software have different capabilities and limitations for handling data. Check the specifications of your software, particularly around row and column limits, to make sure you are using an appropriate tool. 

For example, older versions of Excel (97-2003) have a row limit of 65,000 rows. 

Microsoft has information about [Excel specifications and limits](https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3). 

If you need to share your spreadsheet with people who use earlier versions of Excel, Microsoft has guidance on [making your file backwards compatible](https://support.microsoft.com/en-us/office/use-excel-with-earlier-versions-of-excel-2fd9ffcb-6fce-485b-85af-fecfd651a5ac).

If the spreadsheet tool cannot hold all your data then you are likely to lose information, which can distort statistics and conclusions.

## Use open file formats
Open file formats are standardised file types not tied to one particular software package. Using an open format for your spreadsheet makes it easier for people to use in different tools. 

Open data formats can also make it easier for your organisation to meet legal or compliance obligations. For example, requests for information under the Freedom of Information Act (FOIA) or General Data Protection Act (GDPR) often require data to be provided in a reusable, machine-readable format. 

The open file format for spreadsheets is Open Document Spreadsheet (ODS). Most spreadsheet software allows you to save or export as an ODS file.

Read the guidance on [sharing or collaborating with government documents](https://www.gov.uk/government/publications/open-standards-for-government/sharing-or-collaborating-with-government-documents).

## Use descriptive names
Give your spreadsheet tabs a unique name to help provide context on what information the tab contains. For example, a tab with statistics about wealth and age could be called ‘age_wealth_stats_2019’. This is particularly important if your spreadsheet has or is likely to have multiple tabs.

Filenames are also important to help people find files and understand what they are about. Clear file names:

- use descriptive terms - for example ‘report’, ‘dashboard’, ‘list’
- include a date or date range if relevant, for example ‘January 2019’ or ‘2011 to 2017’
- avoid abbreviations or acronyms that are not widely understood
- avoid special characters or punctuation other than ‘-’ (dash) or ‘_’ (underscore)

If you are creating several versions of a spreadsheet, adding a date or version number will help people find and use the most up to date version. 

## Use versioning to keep track of changes
If you are likely to create, share or maintain different versions of a spreadsheet, it is a good idea to label each version of your spreadsheet. It is particularly important to do this for business critical spreadsheets, for example those shared with a regulator. 

Versioning makes it easier for you and others to:

- find the appropriate version
- keep track of which version has been shared with a particular group
- audit the trail of changes over time
- archive your spreadsheets

You can version your spreadsheet by:

- adding a version number in the filename
- including the version number in the cover page or metadata

Some modern cloud-based storage tools automatically version the documents for you. Ensure you understand the versioning of your file system and environment.

## Use consistent column names 
All column names should follow a consistent naming convention. For example, ‘start_date_time’ and ‘end_date_time’ rather than ‘startdtTime’ and ‘Thetrueend’.

If your spreadsheet uses multiple tabs, and the columns in these tabs hold similar or identical data, use the same column names. For example, in a spreadsheet listing employee satisfaction survey results, use ‘department_name’ in all tabs rather than ‘department_name’ in some and ‘name_of_department’ in others. This will make it easier to cross reference, manipulate or merge columns.

## Check for personal information
Spreadsheets can often contain sensitive or personal information such as names, addresses and health or financial data. Protecting personal information is a legal obligation and important for maintaining credibility and the trust of users and citizens. The Information Commissioner's Office (ICO) has [guidance on personal data and the law](https://ico.org.uk/for-organisations/guide-to-data-protection/introduction-to-data-protection/some-basic-concepts/).

To make sure your spreadsheet does not contain personal information, you should:

- check it twice, then ask someone else from your team to check it again
- do a keyword search for common column names such as “address”, “postcode”, “name”, “dob”, “email”
- check any columns that contain freeform text such as ‘comments’ or ‘feedback’
- check for hidden tabs, columns and rows - read the next section for more information

If your spreadsheet needs to contain personal or sensitive information, mark the spreadsheet as “Official - Sensitive” in the file name or first tab. Make sure to limit access to the spreadsheet only to those who need the information.

## Check for hidden data 
People sometimes hide tabs containing background information for cosmetic or usability reasons. However, before publishing or sharing spreadsheets, you must unhide all tabs, columns and rows and delete any information that should not be shared. This is important to avoid accidentally sharing any data hidden within the spreadsheet that might be sensitive or confidential. 

To be certain you are not including hidden data, export the spreadsheet to CSV as this will export only the information from the current tab and will expose hidden rows or columns. You can then import this data into a completely new spreadsheet to ensure there is no hidden data in the file.

Spreadsheet tools can also store personal information, such as document creator,  in the properties of the document (metadata). This can be useful for internal documents but you may want to remove this information for a public facing document. Microsoft has guidance on how to [view or change the properties for an Office file](https://support.microsoft.com/en-us/topic/view-or-change-the-properties-for-an-office-file-21d604c2-481e-4379-8e54-1dd4622c6b75).
 
## Identify any application code held in your spreadsheet
One benefit of spreadsheets is they can be used as an application development environment to provide additional interactive functionality. 

However, development in spreadsheets rarely has the rigour or structure of larger application development environments. This can be a liability if organisations or departments are dependent on an application that is not well documented or is difficult to maintain.

If your spreadsheet contains code, you should write documentation so developers and other users of the spreadsheet understand:

- the dependence on the code - for example, any systems or processes that could break if the code changes 
- how to minimise potential security liabilities
- what the spreadsheet should be used for, and the scale - typically, this is for smaller departmental tools rather than enterprise applications 

It may be necessary to assess the security risks of any macros or code in your spreadsheet. If you have an IT or Security team, they should be able to help. 

Note that spreadsheet macros will be dropped if the spreadsheet is exported to CSV.

## Avoid hard coded data
Make use of formulas and cell references so your spreadsheet data is as dynamic as possible. 

Hard coded data values can:

- unknowingly cause errors 
- be time-consuming to manually update
- make it difficult for people unfamiliar with the spreadsheet to use it

This is particularly important if your spreadsheet contains calculations or values that are likely to change over time, such as:

- date values, for example the current year
- a total or sum value, for example of a column

You do not need to use dynamic data where a value is truly fixed (for example, pi) or unlikely to change. 

## Optimise for accessibility and machine readability
By law, content published online by the public sector must meet the AA level of the [Web Content Accessibility Guidelines (WCAG) 2.1](https://www.w3.org/TR/WCAG21/). This includes spreadsheets published to public sector websites.

However, accessibility should not simply be a box-checking exercise. Applying accessibility principles to your spreadsheets makes them easier to use for everyone. 

There is some overlap between accessibility and machine readability. Many of the suggestions in this guidance will also make your spreadsheet easier to use with programming tools, as well as software such as screen readers. 

**Note: If the data in your spreadsheet will not be read by humans and only needs to be machine readable, consider [using CSV file format](https://www.gov.uk/guidance/using-csv-file-format).**

To improve the accessibility of your spreadsheets, you should avoid freezing rows and columns as this can limit how much space a user has to navigate the spreadsheet. This can particularly affect users who are using an increased zoom level, a low resolution or a device with a smaller screen. If your spreadsheet is read-only, users may not be able to adjust row and column sizes to suit their viewing needs. 

You should also:

- use the first row on your sheet as the header row containing all the column names
- not use blank or empty rows - if you need more whitespace, adjust the line spacing, row height and column width
- not use merged cells - every cell should contain a value
- not use colour alone to convey meaning, for example using red to highlight important values or cells - use text labels wherever possible
- use only one header row - if you need to group data into further categories, create new columns or use separate tabs for each category

### Example
The following format is not recommended as it introduces a second header row and does not properly link the ‘Continent’ data to the ‘Country’ data: 

| Continent | Country |
| --- | --- |
| Europe | |
| | U.K |
| | Germany | 
| | Italy | 

The following format is correct, as it uses the ‘Continent’ column to categorise each row of country data individually:

| Continent | Country |
| --- | --- |
| Europe | U.K |
| Europe | Germany | 
| Europe | Italy | 

For more guidance on formatting spreadsheets for accessibility and readability, read the [GSS guidance on releasing statistics in spreadsheets](https://gss.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/). Although the guidance is primarily for use with statistics spreadsheets, it can be useful for all types of spreadsheets. 

## Be aware of archiving requirements
Many organisations need to regularly archive published data sets, either for their own auditing purposes, or to meet legal requirements. For example, the National Archives are legally required to archive published data sets from a range of government departments. 

Some of the common challenges when archiving spreadsheets include:

* password protected spreadsheets  - a record of the password will need maintaining indefinitely
* sophisticated spreadsheets, for example those using macros or programming languages like Visual Basic for Applications (VBA) - there is a risk the macro will not run in future versions of the application

You should be aware of how to make sure these files can be accessed in future, particularly if the document will be maintained indefinitely.

**Comment by gheye** [comment]
Please note following conversations with National Archives we will add some additional information around archiving. What works for the National Archives will also assist departments.

**Comment by davidread** [comment]
This is full of distilled, practical and clearly explained advice 👏. I just have few minor suggestions.

> Spreadsheets are a useful way to share data with others.

I wouldn't want this guidance to legitimize or be used to argue for uses of spreadsheet software, in cases where CSV would be more helpful for users. There is a heated debate, so let's be neutral in this guidance.

How about: "Spreadsheets are a **common** way of sharing data with others."

--

In addition, how about a sentence in this introduction to understand the limitations of spreadsheets themselves - when spreadsheets don't suit whole classes of uses/users? This topic is covered very well in the GSS guidance 'Releasing statistics in spreadsheets'](https://gss.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/#part-1-it-s-all-about-the-users) and it doesn't just apply to stats. You could say:

> When sharing or publishing data, consider the needs of users. Spreadsheets can suit [information gatherers](https://gss.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/#part-1-it-s-all-about-the-users). However it can be problematic, for example, for analysts and technical users, who typically need the data in a machine-readable format such as CSV - see the [Tabular Data Standard](https://www.gov.uk/government/publications/recommended-open-standards-for-government/tabular-data-standard).

--

> follow the steps in this guidance to make your file easy to find and use.

I'd add: "and avoid risks" because the last 3 sections are mainly about that.

--

> To make sure your spreadsheet does not contain personal information, you should:

These are useful basic checks, but it would not satisfy more complicated cases, such as [reidentification risks](https://www.theguardian.com/technology/2019/jul/23/anonymised-data-never-be-anonymous-enough-study-finds). It's a complicated area to talk about, so instead I'd simply soften the language to say "Some simple checks for personal information might include:"

**Comment by PeterParslow** [comment]
Hi all,
good to see this developing. I do think that 'spreadsheets' (in CSV format) are a good way to share simple tabular data - but like most 'standards' they do need this kind of supplementary guidance to help people avoid pitfalls.

We (Ordnance Survey) recently did a survey of geospatial data publishers & users (funded by the Geospatial Commission and with the assistance of the Association for Geographic Information) in which we found 

- half of the sixteen publishers who responded use CSV with a particular open standard pattern for expressing geographic coordinates & shapes ("Well Known Text"), although many of them did expect to move away from it in coming years
- one third of the 99 data users who responded listed CSV as a preferred way to receive data - third highest (but the other two are for raster / image data and very structured data), again many expect use to decline but it's certainly popular now

This means there are two minor things we (the geo community) would like to add to the guidance. Perhaps we should create something akin to the guidance specific for statistical data, or perhaps we could provide a short paragraph on how to put a location (or "shape") into the CSV, using "Well Known Text" (WKT).

"Well-known text" was standardised by the Open Geospatial Consortium and is implemented in a lot of different software.

A quick example here, to aid any discussion:

Here's WKT for a point in the OS office, using the default WGS84 long/lat reference system: 

`point(-1.471,50.938)`

Note that the default CRS of WKT is the same as GeoJSON; WGS84 is one of the systems recommended at https://www.gov.uk/government/publications/open-standards-for-government/exchange-of-location-point - but not for use here in UK. To give a WKT point in ETRS89, put the URI for that in front of the point - and swap the coordinates, because it is defined in lat/long!

`http://www.opengis.net/def/crs/EPSG/0/4258 point(50.938,-1.471)` - but less software implements that.

Hence the need for UK guidance!

**Comment by astreater** [comment]
Thank you very much @davidread for this excellent and actionable feedback. I agree with all your points and will be incorporating these suggestions into the draft. 

Instead of 'avoid risks' I would say 'minimise risk' as of course there will always be some amount of risk and we can't guarantee anything! 

For the point about limitations and different user types, this is a point that I have been struggling to articulate so thanks for helping frame it well (and agree, the GSS guidance describes this very well). We are keen to make it clear when to use spreadsheets vs. CSV and vice versa, and want to link to our [CSV guidance](https://www.gov.uk/guidance/using-csv-file-format) in a meaningful way, so I think adding this point, as well as your point about useful/common, will help reinforce these distinctions.

**Comment by gheye** [comment]
Hi @PeterParslow,

Thanks as ever for your comments. 

Would you like us to update the [CSV guidance](https://www.gov.uk/guidance/using-csv-file-format) we published earlier this year to incorporate your comments around geolocation? If so i will add an item into our backlog which is publicly available [here](https://github.com/alphagov/data-standards-authority/projects/1).  Please write the text you would like see here and we will add it. We intend to iterate this guidance later in the year. 

If you would like something specific on Geolocation we can also discuss that offline, and add that to our backlog.

Currently this guidance is specific to spreadsheets. 

Best wishes
@gheye

**Comment by gheye** [comment]
As ever @davidread really appreciate your input.

**Comment by PeterParslow** [comment]
@gheye , sorry for the delay - we were collating the results from surveys we were doing of geo data publishers & geo data users, which has given us some useful insight into what they find works best when exchanging location data in CSV files (even though not all of them do it this way yet) - put simply, the most interoperable way is to adopt the "Well-known text representation of geometry" (https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry); formalised as a standard by [OGC ](https://www.ogc.org) & then the ISO definition of SQL. It's the default output / input of most spatially aware databases systems and other software.

The only counter argument is that in order to fit with [UK government guidance on Coordinate Reference Systems](https://www.gov.uk/government/publications/open-standards-for-government/exchange-of-location-point) each cell in the column would explicitly cite the preferred UK reference system. That part is not described in the Wikipedia page, and I'm not sure how widely it is implemented.

Example: `http://www.opengis.net/def/crs/EPSG/0/4258 point(50.938,-1.471)` is explicitly in one of the preferred systems. The default `point(-1.471,50.938)` not only requires the coordinates in a different order but is currently perhaps 100m away (the UK's preferred system copes with tectonic drift; the default doesn't).

This could be a simple extra paragraph in the CSV guidance, something like:

- if the column contains location data, use the "Well-known text representation of geometry" (https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)

**Comment by gheye** [comment]
Thanks @PeterParslow I have added this request to our backlog which is available [here](https://github.com/alphagov/data-standards-authority/projects/1). 

We are hoping to look at these requests in a few months.

**Comment by astreater** [comment]
We have now published this guidance on GOV.UK - [Creating and sharing spreadsheets](https://www.gov.uk/guidance/creating-and-sharing-spreadsheets). 

If you would like to provide further feedback, please feel free to do so using the feedback tools at the bottom of the published guidance or by contacting us at data-standards-authority@digital.cabinet-office.gov.uk

**Comment by PeterParslow** [comment]
@astreater: I notice that the guidance doesn't contain the suggestion that I made.

- if the column contains location data, use the "Well-known text representation of geometry" (https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)

Is it still part of the backlog that @gheye mentioned, which is not visible to me?

**Comment by gheye** [comment]
@PeterParslow it is a little odd that you cannot click on the link. I think if you copy the link to another tab it should work. 

You can also go to projects>pipeline and it should be visible. 

I have also sent you a screenshot to your email. 

Thanks as ever to your input and to everyone who engaged across government to help us together produce the best guidance possible.

**Comment by PeterParslow** [comment]
Thanks Gareth, the link which was not working for me 22 days ago works for me now. It was probably just the vagary of the internet, which I mistook as being a permissions issue.
